### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by Beebeeoii** [Beebeeoii/lominus#21]
**Is your feature request related to a problem? Please describe.**
Users may tend to annotate on their lecture notes. Having Lominus syncing at selected intervals may overwrite their lecture notes when a newer version is uploaded.

**Describe the solution you'd like**
Have some kind of whitelisting similar to how gitignore.

**Comment by pakshuang** [comment]
Hey thanks for creating this program! Recently I've been looking at the different options out there for syncing luminus files and I've tried out this one! I'm sorry I have 0 experience in Go so I can't help directly implement a solution but I can imagine that there's a few cases to consider here:

1. File on Luminus but not synced locally -> Download
2. File on Luminus and also synced locally based on hash -> No action required
3. File on Luminus and also synced locally based on filename but not hash -> It's been modified by the student, don't overwrite
4. File on Luminus and synced locally based on hash, but the file is updated on Luminus (instructor makes a change) -> Download updated version
5. File on Luminus and synced locally based on filename but not hash (It's been modified by the student), but the file is updated on Luminus (instructor makes a change) -> how now?? Rename the modified file and download the instructor-updated file?
6. File not on Luminus but inside the local folder -> student put their own files in, don't touch

**Comment by Beebeeoii** [comment]
yups thanks for the suggestions ! currently 5 is the issue which requires some attention. I am on the fence with regards to an appropriate and reasonable approach for 5. What I have in mind are:

1. As per your suggestion (rename user's modified file and download the latest file)
2. Move user's modified file to a folder on its own that sits alongside the module folders (?) For eg. user modified `lec1.pdf` in `/MA2001/Lecture/lec1.pdf` and there is a newer update on Luminus, `lec1.pdf` would be moved to `/my-files/MA2001/Lecture/lec1.pdf` and the newer version of `lec1.pdf` would be downloaded.
3. Have a whitelist of files the user would like to annotate on and these files will not be updated

**Comment by pakshuang** [comment]
Yea I feel like 1 would be the cleanest and simplest because 2 would have stuff in more than one place and might also result in the user having to traverse the directory to find their files, 3 would be quite troublesome for the user and also quite risky because they could edit a file and forget to whitelist it and the sync would overwrite their modifications. Just my two-cents! I wish I could contribute but I've never used Go before!
