### ISSUE TITLE
Incorrect folder structure when module has multiple codes

### ISSUE THREAD

**Issue by pakshuang** [Beebeeoii/lominus#24]
**Describe the bug**
Modules that have more than 1 code like SP1541-E1541, ST2131-MA2216 end up creating an additional folder. So instead of `SP1541-E1541\files` you get `SP1541\E1541\files` 

**To Reproduce**
I don't know how this bug can be reproduced without being a student of such a mod

**Expected behavior**
`SP1541-E1541\files`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Beebeeoii** [comment]
yup ! thanks for pointing this out ! I am actually experiencing this myself for ST2131.

should be a quick fix as it wasnt accounted for modules to have names of XXXXXX/XXXXXX (e.g. for a double coded module) which gets translated into nested folders due to the `/`

**Comment by Beebeeoii** [comment]
Issue should be resolved by 41ee722.  Thanks !
