### ISSUE TITLE
Lominus crashes upon sync

### ISSUE THREAD

**Issue by Beebeeoii** [Beebeeoii/lominus#25]
**Describe the bug**
App force quits and crashes upon sync attempts. A pretty difficult bug to reproduce as it occurs only for users with TurnItIn folders in Luminus files. Crashes are linked to absence of response validations.

**Comment by Beebeeoii** [comment]
Tested to be fixed by 3ab8222.

**Comment by kevinchua6** [comment]
Hi, would this be fixed soon? Currently it's unusable for me due to this bug, thank you!

**Comment by Beebeeoii** [comment]
hi this issue should be fixed already under [v1.2.0-alpha](https://github.com/Beebeeoii/lominus/releases/tag/v1.2.0-alpha) but i reopened it just for management convenience as the branch has not been merged into master. forgot to tag and release binaries oops but it is now available as a pre-release.

do let me know if issue persists. cheers !

**Comment by kevinchua6** [comment]
Awesome, it works now! Thank you!
