### ISSUE TITLE
Choose File Directory: Use default file explorer for Windows

### ISSUE THREAD

**Issue by kevinchua6** [Beebeeoii/lominus#60]
**Is your feature request related to a problem? Please describe.**
I feel that it is difficult to find the file location that I want because it's not the integrated one.
![image](https://user-images.githubusercontent.com/45702380/183278152-f181c6d8-0b82-4519-a06d-825a0ff78f4e.png)
Also seems like it's not possible to enter a file directory that I have copied. Seems like we can't create new folders as well?

**Describe the solution you'd like**
It might be better to just use the default file explorer for Windows imo

Related: https://github.com/Beebeeoii/lominus/issues/53

**Comment by Beebeeoii** [comment]
Agree... Will look into bringing back default system file dialogs.

Related commit that removed system dialogs for fyne inbuilt dialogs: https://github.com/Beebeeoii/lominus/pull/33/commits/57577a28a4769dbcc8b458ea30ca5eacc3378a5e
