### ISSUE TITLE
Files in nested folders not downloaded.

### ISSUE THREAD

**Issue by UnderTaker2186** [Beebeeoii/lominus#68]
![image](https://user-images.githubusercontent.com/80204438/183721803-db661bcb-5ed5-4d63-b54a-bb2ded5f1725.png)

![image](https://user-images.githubusercontent.com/80204438/183721460-dedfc1c5-4bf5-4b66-8622-63ffa80b5d05.png)
)
![image](https://user-images.githubusercontent.com/80204438/183721625-e545b542-ecc5-414d-9eb1-52baee85b1cb.png)

![image](https://user-images.githubusercontent.com/80204438/183721876-8bc6cba1-a288-4fef-afdd-e50b7ca2dd30.png)

This occurs when there are subfolders instead of files underneath the folder. The folder is not created and the files inside are not downloaded as well.

**Comment by Beebeeoii** [comment]
closing this issue as it is tested and reported to be fixed by #70
