### ISSUE TITLE
Files in nested folders downloaded but incorrect directory structure

### ISSUE THREAD

**Issue by RussellDash332** [Beebeeoii/lominus#69]
**Describe the bug**
While #68 covers about folders on LumiNUS, this issue is for Canvas. One can download nested files on Canvas but they are not placed on the correct spot.

**Screenshots**
Locally
![image](https://user-images.githubusercontent.com/63991775/183782911-bd254f18-6aec-4126-bdb0-81a07e6b0b87.png)
Expected directory structure
![image](https://user-images.githubusercontent.com/63991775/183782962-401c9fbf-9ce6-4ea7-8364-d6d39857fa93.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 2.0.1

**Comment by Beebeeoii** [comment]
closing this issue as it is tested and reported to be fixed by #70
