### ISSUE TITLE
Files not grouped together in File Explorer

### ISSUE THREAD

**Issue by zupey** [Beebeeoii/lominus#84]
**Is your feature request related to a problem? Please describe.**
Files of the same name are not grouped together in file explorer because the version name is appended to the start of the file name.
This makes it difficult to find the latest version of a particular file.

**Describe the solution you'd like**
Append the version number of the filename to back of the filename instead.
Then, the folder can be ordered by filename then by version number instead of the other way around.

**Additional context**
![image](https://user-images.githubusercontent.com/53803800/187131249-e53fb9df-95df-4d2f-9820-c22f7aac8b91.png)

**Comment by Beebeeoii** [comment]
hi @zupey ! thanks for bringing this up ! i agree with you.

do you think it will be better if we set the convention to be `[name of file] - v[number].pdf`, where the higher the number means the newer the file? this would also mean that `[name of file].pdf` (those without the suffix) will be the very first original ones that are downloaded.

**Comment by zupey** [comment]
Yes, that would make sense. 

If you were referring to the specific way the version number should be displayed, I think any is fine.
`test[v1].pdf` or `test-v1.pdf` is essentially the same thing. Perhaps the former is clearer.

**Comment by Beebeeoii** [comment]
issue resolved by #96
