### ISSUE TITLE
Luminus Sync Error

### ISSUE THREAD

**Issue by BambooOnFire** [Beebeeoii/lominus#86]
Canvas sync works but Luminus sync always produces the message "Verification failed. Please check your credentials."

[2022-09-13 10:09:58] ERROR - EOF (/Users/jiawei/Documents/projects/lominus/internal/cron/cron.go:github.com/beebeeoii/lominus/internal/cron.createJob.func1:127)
[2022-09-13 10:10:02] DEBUG - verifying credentials (/Users/jiawei/Documents/projects/lominus/internal/ui/credentials.go:github.com/beebeeoii/lominus/internal/ui.getLuminusView.func1:107)
[2022-09-13 10:10:02] DEBUG - verfication failed (/Users/jiawei/Documents/projects/lominus/internal/ui/credentials.go:github.com/beebeeoii/lominus/internal/ui.getLuminusView.func1:111)

**Comment by Beebeeoii** [comment]
hi, thanks for reporting this. I assume you are able to login normally via a browser. may I check if this error only occurred recently, or has it always been an issue since day 1? also, may I know what OS are you currently on?

thanks in advance !

**Comment by BambooOnFire** [comment]
This error has only occurred recently (been about 2~3 days) and yes I can log in via browser.

I am using macOS Big Sur 11.6.2

**Comment by Beebeeoii** [comment]
Hi, that's interesting... I suspect that it has something to do with SSL certificates as I have encountered this before on macOS as well (see [FAQ Question 1](https://github.com/Beebeeoii/lominus#faq))

could you navigate to Keychain Access, then find "Entrust Root Certification Authority - G2" under "System Roots". Double click on that and you should see this.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/55170539/190034678-cf797a41-0d7f-4772-bb7f-932599e6173a.png">

The certificate is used by Luminus and should be trusted. If it is already set to "Always trust" or "Use system defaults", try and set it to "Never trust" before toggling it back and see if that resolves the issue.

**Comment by BambooOnFire** [comment]
It sadly did not work...

**Comment by Beebeeoii** [comment]
what version of `openssl` do you have currently? you can check via `openssl version`

**Comment by BambooOnFire** [comment]
The terminal says
`OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)`

**Comment by Beebeeoii** [comment]
ah i see... i am not sure if it would resolve this issue if you were to update it to the latest version (3.0.5). if you are free, could you try updating? not sure about your setup but if you have homebrew installed, i think you can just do `brew update openssl` to update.

**Comment by BambooOnFire** [comment]
I just updated my OpenSSL version to `OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)`
But... the issues persists. :(

**Comment by Beebeeoii** [comment]
oh man :( my guts is telling me it might be because of the recent issues luminus has wrt its authentication service. even on browsers, sometimes i have to relogin multiple times before i can even access my dashboard... not sure if this is actually the root cause as i dont seem to be encountering this issue on Lominus :cry: will need some time to try and figure this out.

in the meantime could you keep this thread updated if it starts working again? thanks so much for reporting this !

**Comment by Beebeeoii** [comment]
does this issue still persists with Canvas?

**Comment by BambooOnFire** [comment]
I just saw the newest release. The assets are not fully available on the user-end so I'll wait a bit till the intel Mac DMG pops up and let you know.

**Comment by Beebeeoii** [comment]
thanks ! it should be up now !

**Comment by BambooOnFire** [comment]
Works like a charm :). Thanks for your hard work.

**Comment by Beebeeoii** [comment]
will be marking this issue as resolved !
