### ISSUE TITLE
Timezone mismatch for file updated Telegram messages

### ISSUE THREAD

**Issue by Beebeeoii** [Beebeeoii/lominus#87]
**Describe the bug**
Telegram messages sent for file updates include a time at which the file was uploaded. This time however, is 8 hours earlier than what it should be because of timezone mismatch (we are in UTC +8 but the message sent did not take that into account).

**Screenshots**
File updated time shown on Canvas is 21:01
![image](https://user-images.githubusercontent.com/55170539/190200104-8838b900-9279-47ca-9679-da7dcf761ee3.png)

File updated time shown on Telegram Message is 13:01 (8 hours earlier)
![image](https://user-images.githubusercontent.com/55170539/190199707-1353f657-7b42-4fb8-adbe-db0fa544d3cd.png)

**Comment by RussellDash332** [comment]
This happens only on Canvas, not Luminus 😄
