### ISSUE TITLE
Lominus will not download from directory with more than 30 items

### ISSUE THREAD

**Issue by markusyeo** [Beebeeoii/lominus#91]
On macos, Lominus is not downloading from Canvas where there are more than 30 items in the source

**Comment by Beebeeoii** [comment]
unfortunately this is due to a bandaid fix from #56. relates to #55. this will be one of the top priority to be fixed next.

**Comment by markusyeo** [comment]
I see, I will just recompile with the same dirty trick and increase the per_page to 100

**Comment by Beebeeoii** [comment]
yup that would work ! pasting here for ease of reference:
https://github.com/Beebeeoii/lominus/blob/63f0c39676848416878dacabd94bf42a218897c5/pkg/constants/endpoints.go#L7-L10

**Comment by Beebeeoii** [comment]
this should be fixed with #102
