### ISSUE TITLE
Lominus downloads new copies of the same file every time it syncs

### ISSUE THREAD

**Issue by GitPancaked** [Beebeeoii/lominus#92]
Every time lominus syncs it creates a new copy of existing files and name them with the prefix [Vx] where x is the copy number. I am on windows 10. 

Additionally, there seems to be no limit to this as I've seen versions go up to 9 or 10, but as a bandaid I just delete the copies every time. Potentially dangerous as it seems to be taking up disk space limitlessly. 

![image](https://user-images.githubusercontent.com/99005378/202894670-00e213eb-653c-49c2-abab-4c90c289e311.png)

**Comment by Beebeeoii** [comment]
hi ! thanks for raising this up. indeed it is quite dangerous and should be looked into asap. is this similar to #88?

**Comment by Beebeeoii** [comment]
hi ! any updates on this issue? do try out the latest release at https://github.com/Beebeeoii/lominus/releases/tag/v2.1.0. thanks !

**Comment by chuakid** [comment]
Hi, problem still exists on v2.1.0.
System: Windows 11
![image](https://user-images.githubusercontent.com/12196891/220532068-c6bb8749-8c4a-4ced-bb42-12800342358e.png)

Logs don't seem to be showing much, mostly normal messages.
```
[2023-02-22 13:37:48] DEBUG - downloading - CS2105/Tutorials/Tutorial_2.pdf [0001-01-01 00:00:00 +0000 UTC vs 2023-01-25 22:59:52 +0800 +08] 
(D:/jiawei/projects/lominus/internal/cron/cron.go:github.com/beebeeoii/lominus/internal/cron.createJob.func1:179)
```
