### ISSUE TITLE
Wrong semester's modules downloaded

### ISSUE THREAD

**Issue by pakshuang** [Beebeeoii/lominus#99]
**Describe the bug**
Only the previous sem's mods seem to be downloading instead of the next sem's mods. Is there a check for the course "term" that only downloads files from mods in a specific sem?

**To Reproduce**
I created a Y2S2 folder for the next sem and synced, Lominus pulled the 4 published mods from last sem and did not pull the 1 published mod for this sem that I had.

**Expected behavior**
Not sure what the intended functionality is, how does Lominus decide which mods to pull?

**Screenshots**
![image](https://user-images.githubusercontent.com/81917538/210691278-622b2547-298d-4b1c-9141-28261bac24ce.png)
ignore DSA2313 that's manually created
![image](https://user-images.githubusercontent.com/81917538/210691395-b99584a5-c1a1-49d0-bdab-1791cee19ef3.png)
HSI2001 folder is not pulled even though the module has files. I'm guessing HS1402S is not pulled because it has no files.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Beebeeoii** [comment]
Hi ! thanks for raising this. The issue on some previous mods being downloaded has been addressed by #98 by only having those starred modules to be downloaded. If user does not star anything, all modules will be downloaded by default.

Will leave this open until the fix is pushed to master and tested to be working. Thanks !

**Comment by pakshuang** [comment]
Thanks! Solid work as usual man

**Comment by Beebeeoii** [comment]
hi ! the latest release is available for download at https://github.com/Beebeeoii/lominus/releases/tag/v2.1.0. do close this issue if its resolved ! thanks !

**Comment by pakshuang** [comment]
I'm running into this issue where the app closes when I click sync. I think Russell told you about it already.

**Comment by Beebeeoii** [comment]
> I'm running into this issue where the app closes when I click sync. I think Russell told you about it already.

lets move this to #103

**Comment by Beebeeoii** [comment]
will close off this issue for now as this should be resolved with #98
